---
title: "Results Summaries"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.path = "../figures/")
knitr::opts_chunk$set(fig.width = 6.5)
knitr::opts_chunk$set(fig.height = 4)
knitr::opts_chunk$set(dev = "png",dpi = 300)

```

```{r}
library(tidyverse)
source(here::here("src", "interval_overlap.R"))

theme_set(theme_minimal())

```

## Load Data

```{r}
scenarios_order <- c("No missing", 
                     "MCAR 0.05", "MCAR 0.10", "MCAR 0.25", "MCAR 0.50", 
                     "MAR 0.05", "MAR 0.10", "MAR 0.25", "MAR 0.50",
                     "MNAR 0.05", "MNAR 0.10", "MNAR 0.25", "MNAR 0.50")

all_results <- bind_rows(
  "No missing" = read_csv(here::here("results", "01_beta_dists.csv")),
  "MCAR 0.05" = read_csv(here::here("results", "02_dists_0.05.csv")),
  "MCAR 0.10" = read_csv(here::here("results", "02_dists_0.1.csv")),
  "MCAR 0.25" = read_csv(here::here("results", "02_dists_0.25.csv")),
  "MCAR 0.50" = read_csv(here::here("results", "02_dists_0.5.csv")),
  "MAR 0.05" = read_csv(here::here("results", "03_dists_0.05.csv")),
  "MAR 0.10" = read_csv(here::here("results", "03_dists_0.1.csv")),
  "MAR 0.25" = read_csv(here::here("results", "03_dists_0.25.csv")),
  "MAR 0.50" = read_csv(here::here("results", "03_dists_0.5.csv")),
  "MNAR 0.05" = read_csv(here::here("results", "04_dists_0.05.csv")),
  "MNAR 0.10" = read_csv(here::here("results", "04_dists_0.1.csv")),
  "MNAR 0.25" = read_csv(here::here("results", "04_dists_0.25.csv")),
  "MNAR 0.50" = read_csv(here::here("results", "04_dists_0.5.csv")),
  .id = "scenario"
)  %>%
  pivot_longer(
    -scenario, 
    names_to = "variable", 
    values_to = "beta"
  ) %>%
  mutate(scenario = factor(scenario, levels = scenarios_order)) #%>%
  #filter(variable=="G2" | variable=="higher_yes")

```

## Compare Samples

```{r posterior-samples, fig.height = 5}
# calculate posterior medians
posterior_medians <- all_results %>%
  group_by(variable, scenario) %>%
  summarize(beta = median(beta)) %>%
  ungroup()

# plot samples and medians
ggplot() +
  geom_point(data = all_results,
             mapping = aes(beta, scenario),
             alpha = 0.2) +
  geom_point(data = posterior_medians,
             mapping = aes(beta, scenario),
             color = "red") +
  facet_wrap(~variable, scales = "free_x", ncol=4) +
  labs(title = "Posterior Samples",
       subtitle = "Posterior medians in red",
       x = "Beta Samples",
       y = NULL)

```

## Compare Posterior Probabilites and Inferences

```{r posterior-probabilities, fig.height = 5}
# calculate posterior probabilities
posterior_probabilities <- all_results %>%
  group_by(scenario, variable) %>%
  summarize(p_gt_0 = mean(beta > 0)) %>%
  ungroup()

# plot posterior probabilities
posterior_probabilities %>%
  ggplot(aes(p_gt_0, scenario)) +
  geom_col() +
  geom_vline(aes(xintercept = 0.05), color = "red") +
  facet_wrap(~variable,
             ncol = 4) +
  labs(title = "Posterior Probabilities",
       subtitle = "0.05 line in red",
       x = "Posterior Probability",
       y = NULL)

```

## Credible Interval Overlap

```{r credible-interval-overlap, fig.height = 3}
# calculate the bounds for the complete data
comp_results <- all_results %>%
  filter(scenario == "No missing") %>%
  group_by(scenario, variable) %>%
  summarize(
    Lcomp = quantile(beta, probs = 0.025),
    Ucomp = quantile(beta, probs = 0.975)
  ) %>%
  ungroup() %>%
  select(-scenario)

# calculate the bounds for the missing data
miss_results <- all_results %>%
  filter(scenario != "No missing") %>%   
  group_by(scenario, variable) %>%
  summarize(
    Lmiss = quantile(beta, probs = 0.025),
    Umiss = quantile(beta, probs = 0.975)
  ) %>%
  ungroup()

# calculate credible interval overlap
cred_interval_overlap <- 
  left_join(miss_results, comp_results, by = "variable") %>%
  mutate(
    interval_overlap =
      interval_overlap(
        Ucomp = Ucomp, 
        Umiss = Umiss, 
        Lcomp = Lcomp, 
        Lmiss = Lmiss
      )
  )
    
# plot the credible interval overlap for each variable
cred_interval_overlap %>%
  filter(variable %in% c("G2", "higher_yes")) %>%  
  ggplot(aes(interval_overlap, scenario)) +
  geom_col() +
  facet_wrap(~variable, nrow = 1) +
  labs(title = "Regression Confidence Interval Overlap",
       x = "Interval Overlap",
       y = NULL)

```

```{r credible-interval-overlap-overall}
# plot the credible interval overlap for each model
cred_interval_overlap %>%
  group_by(scenario) %>%
  summarize(interval_overlap = mean(interval_overlap)) %>%
  ggplot(aes(interval_overlap, scenario)) +
  geom_col() +
  labs(title = "Regression Confidence Interval Overlap",
       x = "Interval Overlap",
       y = NULL)

```

